#!/bin/sh
# Simple boormark browser.

# all boormark lists should be located here
bmpath=$XDG_CONFIG_HOME/bm

choose_cat() {
	{
		find "$bmpath" -type f -printf '%P\n'
		echo '[All]'
	} |
	dmenu -i -l 10 -p 'Category:'
}

choose_urls() {
	test "$1" = '[All]' && shift # cat out all lists
	find "$bmpath/$1" -type f -exec cat {} \; |
	dmenu -i -l 10 -p 'Category:' |
	awk '{
		match($NF, /\[(.*)\]/, url)
		print url[1] }'
}

while : ;do
	cat=$(choose_cat)
	[ -n "$cat" ] || break
	urls=$(choose_urls "$cat")
	[ -n "$urls" ] || continue
	echo "$urls" | xargs -rd'\n' firefox
	break
done
