#!/bin/sh
# Boormark browser.

# all boormark lists should be located here
cd ~/doc/bm || exit 1

while : ;do
	categories=$(find * -type f | dmenu -i -l 10 -p 'Category:')
	[ "$categories" ] || break
	urls=$(
		echo "$categories" |
		xargs -d '\n' sed -z 's/\n\t/\t/g' |
		column -t -s '	' |
		dmenu -i -l 10 -p 'Url:'
	)
	[ "$urls" ] || continue
	echo "$urls" | awk '{print $NF}' | xargs -rd'\n' firefox
	break
done
