#!/bin/sh
# Boormark browser.

# all boormark lists should be located here
cd ~/doc/bm || exit 1

while : ;do
	category=$(ls | dmenu -i -l 10 -p 'Category:') || break
	urls=$(dmenu -i -l 10 -p 'Url:' <"$category") || continue
	echo "$urls" | sed -E 's/.* :: //' | xargs -rd'\n' firefox
	break
done
