#!/bin/sh
# Control the display brightness.

# backlight device name
dev='/sys/class/backlight/intel_backlight'

setenv() {
	[ -r "$dev/brightness" ] && [ -r "$dev/max_brightness" ] || {
		echo "error: cannot read device status: $dev"
		return 1
	}
	read -r curr <"$dev/brightness"
	read -r max <"$dev/max_brightness"
}

chbrt() {
	setenv || return
	[ "$1" -eq "$1" ] 2>/dev/null || {
		echo "error: not an integer: $1" >&2
		return 1
	}
	new=$(((curr*100/max + $1)*max/100 + 1))
	[ -w "$dev/brightness" ] || {
		echo "error: cannot set device brightness: $dev"
		return 1
	}
	echo "$((new < 0 ? 0 : (new > max ? max : new)))" >"$dev/brightness"
}

show() {
	setenv || return
	echo "$((curr * 100 / max))"
}

case $#$1 in
	0) show ;;
	1-*) chbrt "${1#1}" ;;
	1+*) chbrt "${1#1+}" ;;
	*)
		echo "usage: ${0##*/} [+VAL | -VAL]"
		exit 1
esac
