#!/bin/sh
# Control the display brightness.

# backlight device name
dev='/sys/class/backlight/amdgpu_bl0'

chbrt() {
	[ "$2" -gt 0 ] 2>/dev/null || {
		echo "error: not an positive integer: $2" >&2
		return 1
	}
	val=$1$2
	new=$((curr + max*val/100))
	# check bounds and write new value
	echo "$((new < 0 ? 0 : (new > max ? max : new)))" >"$dev/brightness"
}

show() {
	echo "$((curr * 100 / max))%"
}

read -r curr <"$dev/brightness"
read -r max <"$dev/max_brightness"

case $1 in
	show) show ;;
	up) chbrt + "$2" ;;
	down) chbrt - "$2" ;;
	*)
		echo "usage: ${0##*/} { show | up VAL | down VAL }"
		exit 1
esac
