#!/bin/sh
# Record the screen.

# runtime files
lockdir=/tmp/ffrec$DISPLAY
pidfile=$lockdir/pid

# spawn recording processes
record() {
	ffmpeg \
		-loglevel panic \
		-f x11grab \
		-s 1920x1080 \
		-i "$DISPLAY" \
		-f alsa \
		-i hw:0 \
		-r 25 \
		-c:v libx264 \
		-c:a flac \
		"$HOME/video/rec/$(date +'%d-%m-%y_%H:%M:%S').mkv" &
	trap "stop $!" TERM
	wait
}

# kill ffmpeg process (on SIGTERM)
stop() {
	trap '' TERM
	kill "$1"
}

# ignore sigterm for now
trap '' TERM

if mkdir "$lockdir" 2>/dev/null; then
	# recorder branch
	echo $$ >"$pidfile"
	case $(printf '%s\n' yes no | dmenu -l 10 -p 'Start recording?') in
		y*) record ;;
	esac
	rm -r "$lockdir"
else
	# killer branch
	case $(printf '%s\n' yes no | dmenu -l 10 -p 'Stop recording?') in
		y*) pkill -F "$pidfile" 2>/dev/null ;;
	esac
fi
