#!/bin/sh
# View howtos

# file with howtos
howtofile=~/.howto

# check if howto file exists
[ -f "$howtofile" ] || exit

# select topic
topic=$(
	grep -v '^	' "$howtofile"  |
	nl -nln |
	fzf --with-nth 2.. --prompt 'How to> ' |
	cut -f1
)

# check if valid topic was selected
[ "$topic" ] || exit

# display relevant lines from the howto file
awk -v topic="$topic" '{
	if ($0 ~ /^\t/) {
		if (topic_number == topic)
			print substr($0, 2)
	} else {
		if (++topic_number > topic)
			exit
	}
}' "$howtofile"
