#!/bin/sh
# View howtos

# file with howtos
howtofile=~/doc/notes/howto

# select topic
topic=$(
	grep -v '^	' "$howtofile"  |
	nl -nln |
	fzf --with-nth 2.. --prompt 'How to> ' |
	cut -f1
)

# check if valid topic was selected
[ "$topic" ] || exit

# display relevant lines from the howto file
awk -v topic="$topic" '
!/^\t/ {
	topic_number++
	if (topic_number > topic)
		exit
}
/^\t/ {
	if (topic_number == topic)
		print substr($0, 2)
}' "$howtofile"
