#!/bin/sh
# mass mv

# write error message
err() {
	echo "error: $1" >&2
}

# make temporary directory used for file lists
mktmpdir() {
	tmp=$(mktemp -d /tmp/mmvXXX) || {
		err 'failed to create temporary directory'
		return 1
	}
	trap 'rm -rf "$tmp"' EXIT
}

# perform renaming
rename() {
	while read -r old && read -r new; do
		[ "$old" != "$new" ] || continue
		mv -i "$old" "$new"
	done
}

# main routine
mmv() {
	printf '%s\n' "$@" | tee "$tmp/old" >"$tmp/new"
	$EDITOR "$tmp/new" || {
		err "$EDITOR terminated with code $?"
		return 1
	}
	[ "$(wc -l <"$tmp/old")" = "$(wc -l <"$tmp/new")" ] || {
		err 'different line count'
		return 1
	}
	paste -d '\n' "$tmp/old" "$tmp/new" | rename
}

[ $# -gt 0 ] || {
	echo "usage: ${0##*/} FILES..."
	exit
}
[ "$EDITOR" ] || {
	err 'EDITOR variable is not set'
	exit 1
}
mktmpdir && mmv "$@"
