#!/bin/sh
# News viewer for sfeed.

# sfeed files
sfeedroot=~/.sfeed
tsfile=$sfeedroot/last
sfeedpath=$sfeedroot/feeds

# prepend filenames and filter out feeds older than $1
feedfilter() {
	awk -v last="$last" '{
		if ($1 > last)
			print FILENAME "\t" $0
		else
			nextfile
	}' "$@"
}

# format feeds
feedfmt() {
	awk -F '\t' '{
		feed = sprintf("%-20.20s", $1)
		date = strftime("%Y %b %d %H:%M:%S", $2)
		title = sprintf("%-40.40s", $3)
		link = $4
		printf("%s  %s  %s  %s\n", feed, date, title, link)
	}'
}

# list relevant feeds sorted by time
newfeeds() {
	if cd "$sfeedpath" && [ "$(ls)" ]; then
		feedfilter * | sort -t '	' -k2nr,2 | feedfmt
	fi
}

if ! [ -d "$sfeedroot" ]; then
	echo "error: $sfeedroot doesn't exist"
	exit 1
fi

# get last access time
if [ $# -gt 0 ]; then
	last=$(date -d"$*" +%s)
else
	if [ -f "$tsfile" ]; then
		last=$(stat -c%X "$tsfile")
	else
		last=0
	fi
	touch "$tsfile"
	sb upd rss
fi

if ! [ "$last" ]; then
	exit 1
fi

newfeeds |
	dmenu -i -p "Since $(date -d "@$last" +'%Y %b %d %H:%M:%S')" |
	awk '{print $NF}' |
	xargs -rd'\n' firefox
