#!/bin/bash
# Statusbar generator.

# directory for runtime files
tmpdir=/tmp/sb$DISPLAY

# configuration file defining modules and their order
config=~/.scripts/sb.conf

# default option values
output=xrootname
action=start
target=

error() {
	echo "error: $1" >&2
}

showstatus() {
	case $output in
		xrootname) xsetroot -name "$statusline" ;;
		stdout) echo "$statusline"
	esac
}

runck() {
	intv=$1 # interval in seconds
	file=$2 # update file
	[ -f "$tmpdir/$file" ] && {
		rm "$tmpdir/$file"
		return
	}
	[ "$(((tick / 2) % intv))" = 0 ]
}

recompute() {
	statusline=
	for module in "${modules[@]}"; do
		name=${module%%:*} intv=${module#*:}
		runck "$intv" "$name" && "$name"
		if ! [ "$statusline" ]; then
			statusline=${!name}
		else
			statusline+=" | ${!name}"
		fi
	done
	statusline+=' '
}

finish() {
	rm -rf "$tmpdir"
	exit
}

modcfgck() {
	[[ $1 = *:* ]] || {
		error "invalid format: $1"
		return 1
	}
	name=${module%%:*} intv=${module#*:}
	[ "$(type -t "$name")" = function ] || {
		error "not a function: $name in $1"
		return 1
	}
	[ "$intv" -gt 0 ] || {
		error "not a positive integer: $intv in $1"
		return 1
	}
}

loadconfig() {
	source "$config" || {
		error "failed to load configuraiton from $config"
		return 1
	}
	[ "${#modules[@]}" -gt 0 ] || {
		error 'no modules configured'
		return 1
	}
	for module in "${modules[@]}"; do
		modcfgck "$module" || return
	done
}

setup() {
	[ "$DISPLAY" ] || {
		error 'DISPLAY variable is not set'
		return 1
	}
	loadconfig || return
	trap '' TERM INT HUP
	mkdir "$tmpdir" 2>/dev/null || {
		error "statusbar for the display $DISPLAY is already running"
		return 1
	}
	trap finish EXIT TERM INT HUP
}

sbloop() {
	setup || return
	while : ; do
		recompute
		showstatus || return
		tick=$(((tick + 1) % 1000))
		sleep 0.5
	done
}

update() {
	[ "$DISPLAY" ] || {
		error 'DISPLAY variable is not set'
		return 1
	}
	[ "$target" ] || {
		error 'null module name'
		return 1
	}
	touch "$tmpdir/$target" 2>/dev/null
}

while getopts ":xsu:" opt; do
	case $opt in
		x) action=start output=xrootname ;;
		s) action=start output=stdout ;;
		u) action=update target=$OPTARG ;;
		*)
			echo "usage: ${0##*/} { [-xs] | -u MODULE }"
			exit 1
	esac
done

case $action in
	start) sbloop ;;
	update) update ;;
esac
