#!/bin/sh
# Request statusbar update.

# directory for runtime files
tmpdir=/tmp/sb$DISPLAY

error() {
	echo "error: $1" >&2
}

update() {
	for target in "$@"; do
		[ "$target" ] || {
			error 'null module name'
			continue
		}
		touch "$tmpdir/$target" 2>/dev/null
	done
}

[ $# -gt 0 ] || {
	echo "usage: ${0##*/} MODULES..."
	exit 1
}

update "$@"
