#!/bin/sh
# Make screenshot.

# default option values
area=select
save=clip

# make a screenshot
screenshot() {
	case $area in
		full) maim ;;
		select) # make sure touchpad is enabled
			case $(tp state) in
				off)
					tp toggle
					maim -s
					tp toggle ;;
				*) maim -s ;;
			esac
	esac
}

# save image
saveimg() {
	case $save in
		clip) xclip -i -select clipboad -t image/png ;;
		file) cat >"$HOME/pic/screen/$(date +'%d-%m-%y_%H:%M:%S').png" ;;
		open)
			tmp=$(mktemp /tmp/shotXXXX) || return
			cat >"$tmp"
			sxiv "$tmp"
			rm "$tmp"
	esac
}

# parse options
while getopts ':Fof' opt; do
	case $opt in
		F) area=full ;;
		o) save=open ;;
		f) save=file ;;
		*)
			echo "usage: ${0##*/} [-Fof]"
			exit 1
	esac
done

screenshot | saveimg
