#!/bin/sh
# Make screenshot.

# choose area
case $(printf '%s\n' 'Whole screen' 'Select area' | dmenu -p 'Screenshot:' -l 2) in
	W*)
		screenshotcmd() {
			maim
		} ;;
	S*)
		screenshotcmd() {
			# make sure touchpad is enabled
			case $(tp state) in
				off)
					tp toggle
					maim -s
					tp toggle ;;
				*) maim -s ;;
			esac
		} ;;
	*) exit 1 ;;
esac

# choose what to do with a screenshot
case $(printf '%s\n' Clipboad File Open | dmenu -p 'Save to:' -l 3) in
	C*)
		savecmd() {
			xclip -i -select clipboad -t image/png
		} ;;
	F*)
		savecmd() {
			cat >"$HOME/pic/screen/$(date +'%d-%m-%y_%H:%M:%S').png"
		} ;;
	O*)
		savecmd() {
			tmp=$(mktemp /tmp/shotXXXX) || return
			cat >"$tmp"
			sxiv "$tmp"
			rm "$tmp"
		} ;;
	*) exit 1 ;;
esac

# screenshot
screenshotcmd | savecmd
