#!/bin/sh
# Control touchpad state.

# touchpad device name
touchpad='SYNA2BA6:00 06CB:CFD3 Touchpad'

# get current state
cur_state=$(xinput --list-props "$touchpad" | awk '/Device Enabled/ { print $4 }')
[ "$cur_state" ] || {
	echo "${0##*/}: couldn't get current touchpad state" >&2
	exit 1
}

case $1 in
	s|state) # print state
		case $cur_state in
			1) echo on ;;
			0) echo off ;;
			*) echo "${0##*/}: corrupted state value"
		esac ;;
	t|toggle) # toggle state
		case $cur_state in
			1) xinput --disable "$touchpad"; xdotool mousemove 3200 2000 ;;
			0) xinput --enable  "$touchpad"; xdotool mousemove 1600 1000 ;;
			*) echo "${0##*/}: corrupted state value"
		esac ;;
	*)
		echo "usage: ${0##*/} { s[tate] | t[oggle] }"
		exit 1
esac
