#!/bin/sh
# Control touchpad state.

# touchpad device name
name='DELL0767:00 06CB:7E92 Touchpad'

# get current state
cur_state=$(xinput --list-props "$name" | awk '/Device Enabled/ { print $4 }') || {
	echo "${0##*/}: couldn't get current touchpad state" >&2
	exit 1
}

case $1 in
	s*) # print state
		case $cur_state in
			1) echo on ;;
			0) echo off ;;
			*) echo "${0##*/}: corrupted state value"
		esac ;;
	t*) # toggle state
		case $cur_state in
			1) xinput --disable "$name"; xdotool mousemove 1920 0    ;;
			0) xinput --enable  "$name"; xdotool mousemove 960  540  ;;
			*) echo "${0##*/}: corrupted state value"
		esac ;;
esac
