#!/bin/sh
# Control the audio volume.

# change volume level
chvol() {
	amixer -q sset Master 0.75db"$1"
	# update statusbar
	sbupd aud
}

# print volume level in percents
show() {
	info=$(amixer get Master)
	case $info in
		*Mono:*'[on]')
			info=${info#*\[}
			echo "${info%%%\]*}" ;;
		*Mono:*'[off]')
			echo off ;;
		*)
			return 1 ;;
	esac
}

# process arguments
case $1 in
	show) show ;;
	raise) chvol + ;;
	lower) chvol - ;;
	*)
		echo "usage: ${0##*/} { show | raise | lower }"
		exit 1
esac
